description: Software Engineer
author: James E. Torres
theme: jekyll-theme-slate
title: James E. Torres
url: "https://torresjamese.github.io"
disable_disk_cache: true
exclude: [.jekyll-cache, GemFile, Gemfile.lock]
plugins:
  - jemoji
